load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "api_proto",
    srcs = ["api.proto"],
    deps = ["@googleapis//google/api:annotations_proto"],
)

cc_library(
    name = "api",
    srcs = ["api.cc"],
    deps = [":api_proto", "@grpc//:grpc++"],
)
