requires 'Moo', '>= 2.005000, < 3.000000';
requires 'Types::Standard', '== 2.006000';
requires 'Try::Tiny', '>= 0.30, != 0.31';
recommends 'JSON::XS', '>= 4.03';
suggests 'Cpanel::JSON::XS';
conflicts 'JSON', '< 4.00';
