(package "fixture-vcs-default" "0.1.0" "Default VCS branch fixture.")
(depends-on "magit" :git "https://github.com/magit/magit.git")
(depends-on "diff-hl" :git "ssh://git@github.com/dgutov/diff-hl.git" :files ("*.el" "README.md"))
