<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))"
          Condition="'$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))' != ''" />
  <PropertyGroup>
    <SharedPackageVersion>8.0.5</SharedPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="$(SharedPackageVersion)" />
  </ItemGroup>
</Project>
