cabal-version: 3.0
name: example-components
version: 0.1.0.0
build-type: Simple

library
  exposed-modules: Example
  build-depends: base, aeson >=2.1
  default-language: GHC2021

executable example
  main-is: Main.hs
  build-depends: base, example-components, optparse-applicative ^>=0.18
  default-language: Haskell2010

test-suite example-test
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  build-depends: base, example-components, hspec >=2.11
  default-language: Haskell2010
