package analyze

import (
	"path/filepath"
	"testing"
)

func TestTerraformLockFixturesExtractProviderReferences(t *testing.T) {
	tests := []struct {
		name       string
		fixtureDir string
		want       []DependencyReference
	}{
		{
			name:       "Terraform Registry provider with pessimistic constraint",
			fixtureDir: "lock-terraform-registry-pessimistic",
			want: []DependencyReference{
				{PackageType: "generic", Raw: "registry.terraform.io/hashicorp/aws@5.31.0", Name: "registry.terraform.io/hashicorp/aws", Version: "5.31.0", VersionConstraint: "~> 5.31.0", SourceGroup: "providers", OriginKind: OriginRegistry, Relationship: RelationshipDirect, Scope: ScopeRuntime},
			},
		},
		{
			name:       "OpenTofu Registry provider with range constraints",
			fixtureDir: "lock-opentofu-registry-ranges",
			want: []DependencyReference{
				{PackageType: "generic", Raw: "registry.opentofu.org/hashicorp/aws@6.46.0", Name: "registry.opentofu.org/hashicorp/aws", Version: "6.46.0", VersionConstraint: ">= 5.0.0, >= 6.0.0", SourceGroup: "providers", OriginKind: OriginRegistry, Relationship: RelationshipDirect, Scope: ScopeRuntime},
			},
		},
		{
			name:       "Terraform Registry provider without constraints",
			fixtureDir: "lock-terraform-registry-no-constraint",
			want: []DependencyReference{
				{PackageType: "generic", Raw: "registry.terraform.io/hashicorp/google@6.14.0", Name: "registry.terraform.io/hashicorp/google", Version: "6.14.0", SourceGroup: "providers", OriginKind: OriginRegistry, Relationship: RelationshipDirect, Scope: ScopeRuntime},
			},
		},
	}

	ruleset := mustLoadDefaultRules(t)
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			result, err := Scan(filepath.Join("..", "..", "testdata", "terraform", tc.fixtureDir), nil, ruleset)
			if err != nil {
				t.Fatalf("Scan: %v", err)
			}
			source := sourceForPath(t, result, ".terraform.lock.hcl")
			if source.Detector != "terraform-lock" || source.Analysis != (SourceAnalysis{Presence: PresencePresent, Extraction: ExtractionComplete}) {
				t.Fatalf("source = %+v", source)
			}
			if !equalDependencies(source.Dependencies, tc.want) {
				t.Fatalf("dependencies = %#v, want %#v", source.Dependencies, tc.want)
			}
		})
	}
}

func TestTerraformLockWithoutProvidersIsCompleteAndAbsent(t *testing.T) {
	parser, err := newTerraformLockParser(terraformLockMatcherConfig{})
	if err != nil {
		t.Fatalf("newTerraformLockParser: %v", err)
	}
	result, err := parser.Analyze(".terraform.lock.hcl", []byte("# Generated by terraform init.\n"))
	if err != nil {
		t.Fatalf("Analyze: %v", err)
	}
	if !result.Recognized || result.Analysis != (SourceAnalysis{Presence: PresenceAbsent, Extraction: ExtractionComplete}) || len(result.Dependencies) != 0 {
		t.Fatalf("result = %+v", result)
	}
}
