package analyze

import (
	"fmt"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"
)

type yarnLockParser struct{}

const yarnClassicHeader = "# yarn lockfile v1"

type modernYarnLockEntry struct {
	Version    string `yaml:"version"`
	Resolution string `yaml:"resolution"`
}

func (e *modernYarnLockEntry) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("expected mapping node")
	}

	type entry modernYarnLockEntry
	var parsed entry
	if err := value.Decode(&parsed); err != nil {
		return err
	}
	*e = modernYarnLockEntry(parsed)
	return nil
}

func newYarnLockParser(_ yarnLockMatcherConfig) (manifestParser, error) {
	return yarnLockParser{}, nil
}

func (p yarnLockParser) Match(path string, content []byte) (manifestParserResult, error) {
	normalizedContent := normalizeClassicYarnLockContent(string(content))
	if strings.HasPrefix(normalizedContent, yarnClassicHeader) {
		dependencies := parseClassicYarnLockDependencies(normalizedContent)
		if len(dependencies) == 0 {
			return manifestParserResult{
				Matched:         true,
				HasDependencies: boolPtr(false),
			}, nil
		}

		return manifestParserResult{
			Dependencies:    dependencies,
			Matched:         true,
			HasDependencies: boolPtr(true),
		}, nil
	}

	if !strings.HasPrefix(normalizedContent, "__metadata:") {
		normalizedContent = trimLeadingCommentLines(normalizedContent)
	}
	if !strings.HasPrefix(normalizedContent, "__metadata:") {
		return manifestParserResult{}, nil
	}

	dependencies, err := parseModernYarnLockDependencies(path, content)
	if err != nil {
		return manifestParserResult{}, err
	}
	if len(dependencies) == 0 {
		return manifestParserResult{
			Matched:         true,
			HasDependencies: boolPtr(false),
		}, nil
	}

	return manifestParserResult{
		Dependencies:    dependencies,
		Matched:         true,
		HasDependencies: boolPtr(true),
	}, nil
}

func parseModernYarnLockDependencies(path string, content []byte) ([]Dependency, error) {
	var entries map[string]modernYarnLockEntry
	if err := yaml.Unmarshal(content, &entries); err != nil {
		return nil, fmt.Errorf("parse yarn.lock %q: %w", path, err)
	}

	dependencies := make([]Dependency, 0, len(entries))
	seen := make(map[string]struct{}, len(entries))
	for selector, entry := range entries {
		if selector == "__metadata" {
			continue
		}

		name := modernYarnPackageName(selector, entry.Resolution)
		if name == "" {
			continue
		}

		raw := name
		if entry.Version != "" {
			raw += "@" + entry.Version
		}
		if _, ok := seen[raw]; ok {
			continue
		}
		seen[raw] = struct{}{}
		dep := Dependency{Raw: raw, Name: name}
		if entry.Version != "" {
			dep.Version = entry.Version
		}
		dependencies = append(dependencies, dep)
	}

	slices.SortFunc(dependencies, func(a, b Dependency) int {
		if a.Raw < b.Raw {
			return -1
		}
		if a.Raw > b.Raw {
			return 1
		}
		return 0
	})
	return dependencies, nil
}

func normalizeClassicYarnLockContent(content string) string {
	trimmed := strings.TrimLeft(strings.TrimSpace(content), "\ufeff")
	if strings.HasPrefix(trimmed, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n") {
		return strings.TrimPrefix(trimmed, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n")
	}
	return trimmed
}

func trimLeadingCommentLines(content string) string {
	for content != "" {
		lineEnd := strings.Index(content, "\n")
		if lineEnd < 0 {
			lineEnd = len(content)
		}
		line := content[:lineEnd]
		if strings.TrimSpace(line) == "" {
			if lineEnd == len(content) {
				return ""
			}
			content = content[lineEnd+1:]
			continue
		}
		if !strings.HasPrefix(strings.TrimSpace(line), "#") {
			return content
		}
		if lineEnd == len(content) {
			return ""
		}
		content = content[lineEnd+1:]
	}
	return ""
}

func parseClassicYarnLockDependencies(content string) []Dependency {
	lines := strings.Split(content, "\n")
	dependencies := make([]Dependency, 0)
	seen := make(map[string]struct{})

	var selectors []string
	addDependencies := func(selectors []string, version string) {
		for _, selector := range selectors {
			name := classicYarnSelectorName(selector)
			if name == "" {
				continue
			}
			raw := name
			if version != "" {
				raw = name + "@" + version
			}
			if _, ok := seen[raw]; ok {
				continue
			}
			seen[raw] = struct{}{}
			dep := Dependency{Raw: raw, Name: name}
			if version != "" {
				dep.Version = version
			}
			dependencies = append(dependencies, dep)
		}
	}
	flushSelectors := func() {
		if len(selectors) == 0 {
			return
		}
		addDependencies(selectors, "")
		selectors = nil
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			flushSelectors()
			continue
		}

		if strings.HasPrefix(line, "#") {
			continue
		}

		if !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "\t") && strings.HasSuffix(trimmed, ":") {
			flushSelectors()
			selectors = parseClassicYarnLockSelectors(strings.TrimSuffix(trimmed, ":"))
			continue
		}

		if len(selectors) == 0 || !strings.HasPrefix(trimmed, "version ") {
			continue
		}

		version := parseClassicYarnLockVersion(trimmed)
		addDependencies(selectors, version)
		selectors = nil
	}
	flushSelectors()

	return dependencies
}

func parseClassicYarnLockSelectors(header string) []string {
	parts := strings.Split(header, ",")
	selectors := make([]string, 0, len(parts))
	for _, part := range parts {
		selector := strings.TrimSpace(part)
		selector = strings.Trim(selector, `"`)
		if selector == "" {
			continue
		}
		selectors = append(selectors, selector)
	}
	return selectors
}

func parseClassicYarnLockVersion(line string) string {
	value := strings.TrimSpace(strings.TrimPrefix(line, "version"))
	return strings.Trim(value, `"`)
}

func classicYarnSelectorName(selector string) string {
	if selector == "" {
		return ""
	}

	start := 0
	if strings.HasPrefix(selector, "@") {
		start = 1
	}

	index := strings.Index(selector[start:], "@")
	if index < 0 {
		return selector
	}
	return selector[:start+index]
}

func modernYarnPackageName(selector string, resolution string) string {
	if name := modernYarnSelectorName(resolution); name != "" {
		return name
	}
	for _, part := range strings.Split(selector, ",") {
		if name := modernYarnSelectorName(strings.TrimSpace(part)); name != "" {
			return name
		}
	}
	return ""
}

func modernYarnSelectorName(selector string) string {
	selector = strings.Trim(selector, `"`)
	if selector == "" {
		return ""
	}

	start := 0
	if strings.HasPrefix(selector, "@") {
		start = 1
	}

	index := strings.Index(selector[start:], "@")
	if index < 0 {
		return selector
	}
	return selector[:start+index]
}
